### ISSUE TITLE
module 'ArducamDepthCamera' has no attribute 'ArducamCamera'

### ISSUE THREAD

**Issue by Coimbra1984** [ArduCAM/Arducam_tof_camera#31]
Hi,

I installed the python dependencies (I work on a raspberry 4) as described in the README, however I get the following error message:

```
Python 3.9.2 (default, Mar 12 2021, 04:06:34)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ArducamDepthCamera as ac
>>> cam = ac.ArducamCamera()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ArducamDepthCamera' has no attribute 'ArducamCamera'

```

**Comment by dennis-ard** [comment]
Hello,
Can you provide the SDK version you use? If the version of the SDK is less than 0.0.10, this may be the cause of the problem.
Please use the shell command to provide me with information:
```Shell
  pip3 list | Grep arducamdepthcamera
```
If the SDK version is less than 0.0.10, please try it again after updating.

**Comment by Lunacyworks** [comment]
I am using 0.0.11 and get the following error

Traceback (most recent call last):
  File "/home/rpi4/Arducam_tof_camera/demo.py", line 51, in <module>
    if cam.init(ac.TOFConnect.CSI,ac.TOFOutput.DEPTH,0) != 0 :
AttributeError: 'ArducamDepthCamera.ArducamDepthCamera.ArducamCamer' object has no attribute 'init'

**Comment by dje666** [comment]
I get the same error with the latest Module.?

<img width="698" height="141" alt="Image" src="https://github.com/user-attachments/assets/631e655d-bd2f-48bc-9f11-aea7730ae3ae" />

Any ideas?

Regards,

DJE666
